version: 1.0.{build}
build_cloud: libcc-20
image: libcc-20-vs2017
clone_folder: c:\build
environment:
  matrix:
  - TARGET_ARCH: ia32
    COMPONENT: shared_library
  - TARGET_ARCH: x64
    COMPONENT: shared_library
  - TARGET_ARCH: ia32
    COMPONENT: static_library
  - TARGET_ARCH: x64
    COMPONENT: static_library
build_script:
- ps: >-
    if(($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME -split "/")[0] -eq ($env:APPVEYOR_REPO_NAME -split "/")[0]) {
      Write-warning "Skipping PR build for branch"; Exit-AppveyorBuild
    } else {
      if($env:APPVEYOR_SCHEDULED_BUILD -eq 'True')  {
        script\cibuild.ps1 -buildTests
      } else {
        script\cibuild.ps1
      }
      if ($? -ne 'True') {
        throw "Build failed with exit code $?"
      } else {
        "Build succeeded."
      }
    }
test_script:
- ps: >-
    if($env:COMPONENT -eq 'static_library' -And $env:APPVEYOR_SCHEDULED_BUILD -eq 'True')  {
      python script\run_tests --generate_report -t $env:TARGET_ARCH
      npm install -g junit-merge
      junit-merge -d test_reports
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://windows-ci.electronjs.org/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\merged-test-results.xml))
    } else {
      Write-Output "Skipping tests for shared_library build"
    }

artifacts:
- path: libchromiumcontent.zip
  name: libchromiumcontent.zip
- path: libchromiumcontent-static.zip
  name: libchromiumcontent-static.zip
- path: 'merged-test-results.xml'
  name: tests
